### ISSUE TITLE
layer fences

### ISSUE THREAD

**Issue by tyler-utah** [johnwickerson/memalloy#10]
Fences that are strictly stronger than each other should contain both the strong and weak annotation. This makes reducing the tests straightforward.

**Comment by johnwickerson** [comment]
I'm setting things up so that:
* in ARM, `dmb` implies `dmb.st`, and `dmb` implies `dmb.ld` (and `isb`s are incomparable),
* in Power, `sync` implies `lwsync`, and `sync` implies `eieio`, (and `isync`s are incomparable), and
* in PTX, `membar.sys` implies `membar.gl`, and `membar.gl` implies `membar.cta`.

Does that sound about right?

**Comment by tyler-utah** [comment]
The PTX ones look good!

By transitivity membar.sys implies membar.cta right?

**Comment by johnwickerson** [comment]
Right!
